"""Operation-level synthesis (manuscript §3.5) and the library steward queue, from the active release.

Reads the published component-library projection and the per-record decomposition statuses.
Reuse is measured as distinct records per operation; calls inside one paper count once.
"""

import json
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / "docs/input-representation-atlas/component-library/data"
RUN = ROOT / "analysis/operation_decomposition_2026-10-07"
OUT = ROOT / "analysis/review_synthesis_2026-10-07"


def main():
    catalog = json.loads((PUBLIC / "catalog.json").read_text())
    assemblies = json.loads((PUBLIC / "assemblies.json").read_text())
    records = catalog["records"]
    pilot = {r for r, v in records.items() if "decomposition_status" not in v}
    papers = len(records)

    reuse = {b["operation_id"]: {"label": b["label"], "papers": len(b["reuse_record_ids"]), "calls": len(b["usage"])}
             for b in catalog["blocks"]}
    per_paper = defaultdict(lambda: {"library": 0, "unexpanded": 0, "operations": set()})
    params = defaultdict(lambda: Counter())
    for a in assemblies:
        row = per_paper[a["record_id"]]
        for c in a["calls"]:
            if c["operation_id"]:
                row["library"] += 1
                row["operations"].add(c["operation_id"])
                if a["record_id"] in pilot:
                    continue  # pilot adapter writes fixed placeholders (e.g. trainability); not comparable coding
                for name, value in c["parameters"].items():
                    if name != "source_port_roles":
                        params[(c["operation_id"], name)]["unspecified" if str(value).strip().lower().startswith("unspecified") else "stated"] += 1
            else:
                row["unexpanded"] += 1
    shares = sorted(r["unexpanded"] / (r["library"] + r["unexpanded"]) for r in per_paper.values() if r["library"] + r["unexpanded"])
    declared = {b["operation_id"]: b["parameters"] for b in catalog["blocks"]}
    realisation = []
    for op, names in declared.items():
        for name in names:
            c = params[(op, name)]
            total = c["stated"] + c["unspecified"]
            if total >= 1:
                realisation.append({"operation_id": op, "parameter": name, "calls": total, "stated": c["stated"],
                                    "unspecified_share": round(c["unspecified"] / total, 3)})
    realisation.sort(key=lambda r: (-r["calls"], r["operation_id"]))

    statuses = [json.loads(p.read_text()) for p in sorted((RUN / "records").glob("*/status.json"))]
    open_types, open_by_paper, proposals = Counter(), {}, []
    for s in statuses:
        reviews = sorted((RUN / "records" / s["record_id"]).glob("review_round_*.json"),
                         key=lambda p: int(p.stem.rsplit("_", 1)[1]))
        if reviews:
            findings = [f for f in json.loads(reviews[-1].read_text())["findings"] if f["severity"] == "blocking"]
            open_types.update(f["issue_type"] for f in findings)
            open_by_paper[s["record_id"]] = len(findings)
        proposals += [dict(p, record_id=s["record_id"]) for p in s.get("operation_proposals", [])]
    boundary_labels = Counter({p["source_operation"]: len(p["occurrences"]) for p in catalog["pending"]})

    summary = {
        "release": catalog["release"], "papers": papers, "pilot_papers": len(pilot), "agent_papers": papers - len(pilot),
        "trajectories": len(assemblies), "library_calls": catalog["report"]["primitive_calls"],
        "unexpanded_steps": catalog["report"]["unexpanded_source_steps"],
        "unexpanded_labels": catalog["report"]["unexpanded_source_labels"],
        "operations_reused_by_2plus_papers": sum(1 for v in reuse.values() if v["papers"] >= 2),
        "operation_reuse": dict(sorted(reuse.items(), key=lambda kv: -kv[1]["papers"])),
        "operations_per_paper": dict(sorted(Counter(len(r["operations"]) for r in per_paper.values()).items())),
        "unexpanded_share_per_paper": {"median": shares[len(shares) // 2], "min": shares[0], "max": shares[-1]},
        "parameter_realisation_scope": "agent-decomposed papers only (pilot adapter placeholders excluded)",
        "parameter_realisation": realisation,
        "open_blocking_by_type": dict(open_types.most_common()),
        "open_blocking_total": sum(open_types.values()),
        "papers_without_open_blocking": sum(1 for v in open_by_paper.values() if v == 0),
        "operation_proposals": len(proposals),
        "top_boundary_labels": boundary_labels.most_common(25),
    }
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "operation_synthesis.json").write_text(json.dumps(summary, indent=2) + "\n")

    lines = [f"# Library steward queue (release {catalog['release']})", "",
             "Generated by `scripts/build_operation_synthesis.py`. Work items for the library steward, in order:", "",
             f"1. **Open reviewer findings**: {summary['open_blocking_total']} blocking findings across "
             f"{len(open_by_paper) - summary['papers_without_open_blocking']} agent-decomposed papers. Per-paper detail is in "
             "`analysis/operation_decomposition_2026-10-07/records/<record>/review_round_*.json` and on each chain's page.",
             f"2. **Operation proposals**: {len(proposals)} agent proposals for computations no catalog operation represents.",
             f"3. **Unexpanded boundaries**: {summary['unexpanded_steps']} steps under {summary['unexpanded_labels']} labels; "
             "group recurring labels and decide whether an existing operation, a new operation, or a retained module boundary applies.",
             "", "## Open blocking findings by type", "", "| Issue | n |", "|---|---:|"]
    lines += [f"| {k.replace('_', ' ')} | {v} |" for k, v in open_types.most_common()]
    lines += ["", "## Papers by open blocking findings", "", "| Record | Paper | Open blocking |", "|---|---|---:|"]
    lines += [f"| `{r}` | {records.get(r, {}).get('paper', '(not published)')} | {n} |"
              for r, n in sorted(open_by_paper.items(), key=lambda kv: -kv[1])]
    lines += ["", "## Operation proposals", "", "| Record | Proposed computation | Compared operations | Why no existing operation |", "|---|---|---|---|"]
    lines += [f"| `{p['record_id']}` | {p['source_operation']} | {', '.join(p['compared_operation_ids'])} | "
              f"{p['why_no_existing_operation'].replace('|', '/')} |" for p in proposals]
    lines += ["", "## Most frequent unexpanded boundary labels", "", "| Label | Steps |", "|---|---:|"]
    lines += [f"| `{k}` | {v} |" for k, v in boundary_labels.most_common(40)]
    (RUN / "STEWARD_QUEUE.md").write_text("\n".join(lines) + "\n")
    print(json.dumps({k: summary[k] for k in ("papers", "trajectories", "library_calls", "unexpanded_steps",
                                               "operations_reused_by_2plus_papers", "unexpanded_share_per_paper",
                                               "open_blocking_total", "papers_without_open_blocking", "operation_proposals")}, indent=1))


if __name__ == "__main__":
    main()
